version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5999:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: pow
    networks:
      - pow-network
networks:
  pow-network:
